# Basic image recognition with Tensorflow and Keras

First lab using neural networks This training is intended to be my notes around training and hopefully somebody else will find it useful. I don't take any credit for making this lab.

Taken from: https://github.com/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb

Tensorflow is the open source machine learning framework that I'll be learning over the next weeks and months. Google created (no surprise).

In [42]:
import tensorflow as tf

We're importing the MNIST database, a handwritten images database, which we can use for identifying characters (numbers or letters) through machine learning.


https://keras.io/api/datasets/mnist/

In [28]:
mnist = tf.keras.datasets.mnist

You are creating **four** portions of data which will be used for fitting and predicting values.

1. X_train - It is the set of independent variables that will be used to train the model

2. X_test - It is the set of independent variables that will be used to test the model

3. y_train - This data has category labels used to train data, namenly, your dependent variable. 

4. y_test - This data has category labels to test your data.


In [43]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

We are creating the model based on Keras, and assigning each layer different functions used to train our model (which honestly I don't yet understand)

In [44]:
# Create our model

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [33]:
predictions = model(x_train[:1]).numpy()

In [34]:
predictions

array([[ 0.35657528, -0.07919221,  0.51683813,  0.05476549,  0.5040275 ,
         0.01421949,  0.1688686 , -0.11529364,  0.31366864, -0.01958811]],
      dtype=float32)

In [35]:
# Convert these logits to probabilities
tf.nn.softmax(predictions).numpy()

array([[0.11728521, 0.07585634, 0.13767165, 0.08672991, 0.13591924,
        0.0832837 , 0.09721275, 0.07316665, 0.11235932, 0.08051514]],
      dtype=float32)

In [36]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [37]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [38]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2940 - accuracy: 0.9125
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1402 - accuracy: 0.9580
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1054 - accuracy: 0.9684
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0875 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0747 - accuracy: 0.9771


In [39]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0711 - accuracy: 0.9778


[0.07114116847515106, 0.9778000116348267]

In [40]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.58036106e-07, 3.97703116e-06, 4.43242971e-05, 1.11021311e-03,
        4.24451307e-11, 4.43759774e-07, 4.67822124e-13, 9.98823583e-01,
        1.51617769e-06, 1.53634937e-05],
       [1.78469545e-10, 1.65158854e-05, 9.99931931e-01, 5.13171472e-05,
        7.76003858e-18, 6.49097771e-08, 3.47608022e-08, 1.29297684e-15,
        1.35937739e-07, 1.18282417e-14],
       [1.17716617e-07, 9.99560416e-01, 2.28765293e-05, 7.42303428e-06,
        2.92751010e-05, 2.22177150e-05, 3.96383439e-05, 1.91059196e-04,
        1.24512182e-04, 2.45100341e-06],
       [9.99752700e-01, 3.50175638e-10, 1.11827074e-04, 1.42795457e-07,
        2.44151011e-06, 3.15700818e-05, 1.61366206e-05, 2.27923792e-05,
        2.22918519e-08, 6.24026798e-05],
       [4.29212241e-06, 1.80155588e-08, 3.09738316e-05, 6.61017566e-07,
        9.97534156e-01, 1.35106911e-05, 4.38344796e-06, 5.18756815e-06,
        2.72322995e-06, 2.40409374e-03]], dtype=float32)>